Fix schema resolution using Samba share on Windows
keesschollaart81/vscode-home-assistant pull request #3313
Opened 2024-12-01 12:40 UTC by edoren

Hello!

While using this extension via the Samba share addon on Windows I noticed that the schemas were not working properly, in the logs I noticed that only the first backslash was being replaced and this was triggering the issue in the schema resolution of `yaml-language-server`:

```
Applying schemas to 10 of your configuration files...
Assigning /%5C192.168.1.102%5Cconfig%5Cconfiguration.yaml the configuration.yaml schema
Assigning /%5C192.168.1.102%5Cconfig%5Cautomations.yaml the configuration.yaml/automation schema
Assigning /%5C192.168.1.102%5Cconfig%5Cautomations.yaml the configuration.yaml/automation schema
Assigning /%5C192.168.1.102%5Cconfig%5Cscripts.yaml the configuration.yaml/script schema
Assigning /%5C192.168.1.102%5Cconfig%5Cscenes.yaml the configuration.yaml/scene schema
Assigning /%5C192.168.1.102%5Cconfig%5Cbinary_sensor.yaml the configuration.yaml/binary_sensor schema
Schemas updated!
```

I also saw this [comment](https://github.com/keesschollaart81/vscode-home-assistant/issues/1002#issuecomment-881968808) from someone that had a similar issue. After this change the entry is registered properly and the schemas work:

```
Applying schemas to 10 of your configuration files...
Assigning //192.168.1.102/config/configuration.yaml the configuration.yaml schema
Assigning //192.168.1.102/config/automations.yaml the configuration.yaml/automation schema
Assigning //192.168.1.102/config/automations.yaml the configuration.yaml/automation schema
Assigning //192.168.1.102/config/scripts.yaml the configuration.yaml/script schema
Assigning //192.168.1.102/config/scenes.yaml the configuration.yaml/scene schema
Assigning //192.168.1.102/config/binary_sensor.yaml the configuration.yaml/binary_sensor schema
Schemas updated!
```

2024-12-11 08:09 UTC, frenck requested changes
Hi there @edoren 👋 

The CI is failing, could you please take a look?

Thanks! 👍 

../Frenck

2024-12-11 11:45 UTC, edoren commented
It seems `replaceAll` is part of es2021, I can do the change to update it on the `tsconfig.json`, but before that, is there any reason why es2020 is still used?

2024-12-12 20:09 UTC, frenck commented
@edoren I wish I could tell you :) I'm not a JS developer at all.

../Frenck

2025-01-04 15:09 UTC, frenck approved these changes
Thanks, @edoren 👍 

../Frenck

2025-01-04 15:09 UTC, merged

2025-01-04 15:27 UTC, edoren commented
Sorry I noticed a check failed, I'm fixing it right away!